import MenuBlock from '../components/MenuBlock';
import { FooterBlock } from '../components/FooterBlock';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
    return (
        <html lang='ru-luna1918'>
            <body>
                <MenuBlock />
                {children}
                <FooterBlock />
            </body>
        </html>
    );
}
